dataset: # Required.
  type: costum_tif
  data_root: E:\dataset\dq_road
  convertLabel: {1: 1}
  train:
    data_list: train.txt
    flip: True
    GaussianBlur: False
    ColorJitter: True
#    resize: [512,512]
    rand_resize: [0.75, 1.5]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [512, 512] # crop image with HxW size
  val:
    data_list: val.txt
    resize: [512,512]
  test:
    data_list: val.txt
    vis_path: E:\dataset\dq_road\vis3
##    crop:
##      type: center
#      size: [512,512] # crop image with HxW size
  batch_size: 6
  noise_std: 0.1
  workers: 8
  category: {1: "road"}
#  mean: [123.675, 116.28, 103.53]
#  std: [58.395, 57.12, 57.375]
  ignore_label: 255
trainer: # Required.
  epochs: 100
  iter_vis: 10
  start_epochs: 0
  eval_on: True
  optimizer:
    type: adam
    kwargs:
      lr: 0.00005  # 2GPUs
      head_lr_rate: 1
      momentum: 0.9
      weight_decay: 0.0
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
      milestones: [50, 75]

saver:
  exp_path: ckpt
  log_path: log
  task_name: road_dq
  task_idx: unet_r50_3

criterion:
  type: focal
  cls_weight: [1,6]
  dice_loss: True
  kwargs:  
    use_weight: False

net: # Required.
  num_classes: 2
  sync_bn: True
  ema_decay: 0.99
  base_model: unet
  backbone: resnet50
  attn:
    name: CBAM  # SE, ECA, CBAM
    mode: FC  # FC, Conv
    pool: avg  # avg, max
  pretrain: 'E:\python\ZEV\U2PL\ckpt\costum_tif\road_dq\unet_r50_2\best_epoch_weights.pth'
