dataset: # Required.
  type: costum_semi
  data_root: D:\DATA\DQ3
  train:
    data_list: train1.txt
    unlabel_data_list: unlabel.txt
    flip: True
    GaussianBlur: False
    #rand_resize: [1.0, 1.0]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [512, 512] # crop image with HxW size
  val:
    data_list: val1.txt
    crop:
      type: center
      size: [512, 512] # crop image with HxW size
  batch_size: 2
  noise_std: 0.1
  workers: 8
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255  #

trainer: # Required.
  epochs: 50
  sup_only_iter: 1000
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.0002  # 4GPUs
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
  unsupervised:
    TTA: False
    drop_percent: 80
    apply_aug: cutmix
  contrastive:
    negative_high_entropy: True
    low_rank: 2
    high_rank: 5
    current_class_threshold: 0.3
    current_class_negative_threshold: 1
    unsupervised_entropy_ignore: 80
    low_entropy_threshold: 20
    num_negatives: 50
    num_queries: 256
    temperature: 0.5

saver:
  exp_path: ckpt
  log_path: log
  task_name: dq
  task_idx: dq_deep_r50_2

criterion:
  type: CELoss
  kwargs:
    use_weight: False

net: # Required.
  num_classes: 6
  base_model: deeplab
  pretrain: 'E:\python\ZEV\U2PL\ckpt\costum_semi\dq\dq_deep_r50_2\ckpt_best.pth'
  sync_bn: True
  ema_decay: 0.999
  backbone: resnet50
  encoder:
    type: u2pl.models.resnet.resnet50
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: u2pl.models.decoder.dec_deeplabv3_plus
    kwargs:
      inner_planes: 256
      dilations: [12, 24, 36]
