dataset: # Required.
  type: costum
  data_root: D:\DQ
  train:
    data_list: train.txt
    flip: True
    GaussianBlur: False
    ColorJitter: True
    rand_resize: [ 0.5, 2.0 ]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [512, 512] # crop image with HxW size
  val:
    data_list: val.txt
    crop:
      type: center
      size: [512,512] # crop image with HxW size
  batch_size: 6
  noise_std: 0.1
  workers: 8
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 100
  start_epochs: 0
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.0001  # 2GPUs
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: step
    kwargs:
      power: 0.9
      milestones: [60, 80]

saver:
  exp_path: ckpt
  log_path: log
  task_name: dq0
  task_idx: unet_r50_1

criterion:
  type: focal
  cls_weight: []
  dice_loss: True
  kwargs:
    use_weight: False

net: # Required.
  num_classes: 6
  sync_bn: True
  ema_decay: 0.99
  base_model: unet
  backbone: resnet50
  pretrain: 'E:\python\ZEV\unet-pytorch\model_data\unet_resnet_voc.pth'

