dataset: # Required.
  type: costum
  train:
    data_root: D:\DQ
    data_list: D:\DQ\train.txt
    flip: True
    GaussianBlur: False
#    rand_resize: [0.5, 2.0]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [512, 512] # crop image with HxW size
  val:
    data_root: D:\DQ
    data_list: D:\DQ\val.txt
    crop:
      type: center
      size: [512,512] # crop image with HxW size
  batch_size: 6
  noise_std: 0.1
  workers: 8
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 50
  start_epochs: 0
  eval_on: True
  optimizer:
    type: SGD
    kwargs:
      lr: 0.0004  # 2GPUs
      momentum: 0.9
      weight_decay: 0.0001
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9

saver:
  exp_path: ckpt
  log_path: log
  task_name: dq
  task_idx: dq2

criterion:
  type: CELoss
  kwargs:  
    use_weight: False

net: # Required.
  num_classes: 6
  sync_bn: True
  ema_decay: 0.99
  base_model: naic
  pretrain: 'E:\python\ZEV\U2PL\ckpt\pretrain\last_try_best\Deeplabv3.pth'
  encoder:
    type: u2pl.models.resnet.resnet101
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: u2pl.models.decoder.dec_deeplabv3_plus
    kwargs:
      rep_head: False
      inner_planes: 256
      dilations: [12, 24, 36]
